name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Default steps
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use Yarn
        run: |
          echo -e "\e[36m Use Yarn - Yarn version: \e[0m $(yarn --version)" 
          yarn

      - name: Build
        run: |
          echo -e "\e[36m Build \e[0m" 
          yarn run build

      - name: Linter
        run: |
          echo -e "\e[36m Linter \e[0m" 
          yarn run style:all
